### PR TITLE
Feature: support short-uuids

### LINKED ISSUE #1: extend to include short-uuid
I believe we can be extended this package to include short uuids by using the crate [short-uuid](https://github.com/radim10/short-uuid)

### PR DESCRIPTION
**Pull request by DyfanJones**
Extends uwu to support basic short-uuids implementation.

Fixes: #1

### CODE REVIEW

**Comment by JosiahParry** [comment]
Looks brilliant!!! Do you think we can rename short_uuid() to new_short() to be like the new_v4 and new_v7?

**Comment by DyfanJones** [comment]
Sure thing. I have just realised short-uuid allows shorts to be converted back. Will add that as well

**Comment by DyfanJones** [comment]
@JosiahParry what is your take on converting invalid uuid's. Currently it will do the following:

``` r
uuid <- c("bf34000c-3779-4519-a82f-8c8b45b80dab", NA, "123", "")
uwu::uuid_to_short(uuid)
#> Error in uuid_to_short_flickr_(uuid): user function panicked: uuid_to_short_flickr_
```

<sup>Created on 2024-08-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Alternatively we could just default to empty strings when it fails to convert:
``` r
uuid <- c("bf34000c-3779-4519-a82f-8c8b45b80dab", NA, "123", "")
uwu::uuid_to_short(uuid)
#> [1] "pBpYVoXrShgRxX5o3yg6Kz" ""                       ""                      ""
```

Or return the values back.

``` r
uuid <- c("bf34000c-3779-4519-a82f-8c8b45b80dab", NA, "123", "")
uwu::uuid_to_short(uuid)
#> [1] "pBpYVoXrShgRxX5o3yg6Kz" NA  "123"  ""
```

For the other 2 methods we should return and warning message so the user knows it has failed to convert. **Note** this will also need to be considered when converting short uuids back into uuids.

**Comment by JosiahParry** [comment]
Thank you! I think we can catch the `Err` and return an NA in that case. We could use `std::cell::OnceCell` to track and set a flag if an error was encountered. At the end of iteration that can be used to determine whether a warning should be emitted. 

I think failing is a little aggressive.

**Comment by JosiahParry** [comment]
Let me know if you want a hand on this. I should be able to assist on Monday or later—in the middle of a move!

**Comment by DyfanJones** [comment]
Not sure how to do this bit:

> We could use std::cell::OnceCell to track and set a flag if an error was encountered. At the end of iteration that can be used to determine whether a warning should be emitted.

I keep going back and forth if we need it or not 🤔 

> Let me know if you want a hand on this. I should be able to assist on Monday or later—in the middle of a move!

No rush, it helped me improve my limited rust knowledge 😄

**Comment by JosiahParry** [comment]
I think documenting thst invalid uuids become NA is sufficient. Great work on the match statements these look great!

**Review by JosiahParry — APPROVED** [review]

**Pull request merged**
